[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
payx_escrow = "CTFbnKuiHpg5PR5vHpBXJzvLyCGrhMuQp4PbK8ZRGboa"

[programs.localnet]
payx_escrow = "11111111111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm exec tsx --test tests/**/*.test.ts"
